#
# Makefile
#
# Makefile for xitech
#

.PHONY: clean all

clean all:
	$(MAKE) -C XDBotThermometer $(MAKECMDGOALS)
	$(MAKE) -C XDBotAlarmer $(MAKECMDGOALS)
	$(MAKE) -C XDBotDataInboundService $(MAKECMDGOALS)
	$(MAKE) -C XDBotDataOutboundService $(MAKECMDGOALS)
	$(MAKE) -C Streamer $(MAKECMDGOALS)
